auto Mode: on
eventtime: 19:08:00, nextTime: 23:59:00, curentTime: 15:37:00
eventname: off
curEvent: 
UPDATED: 15:37:00
eventtime: 19:07:00, nextTime: 19:08:00, curentTime: 15:37:00
eventname: on
curEvent: 
UPDATED: 15:37:00
eventtime: 05:57:00, nextTime: 19:07:00, curentTime: 15:37:00
eventname: test2
curEvent: 
eventtime: 18:20:00, nextTime: 19:07:00, curentTime: 15:37:00
eventname: test
curEvent: 
UPDATED: 15:37:00
Traceback (most recent call last):
  File "/home/jeff/minitree/app.py", line 135, in <module>
    serve(app, host='0.0.0.0', port=PORT)
  File "/usr/local/lib/python3.9/dist-packages/waitress/__init__.py", line 13, in serve
    server = _server(app, **kw)
  File "/usr/local/lib/python3.9/dist-packages/waitress/server.py", line 78, in create_server
    last_serv = TcpWSGIServer(
  File "/usr/local/lib/python3.9/dist-packages/waitress/server.py", line 243, in __init__
    self.bind_server_socket()
  File "/usr/local/lib/python3.9/dist-packages/waitress/server.py", line 364, in bind_server_socket
    self.bind(sockaddr)
  File "/usr/local/lib/python3.9/dist-packages/waitress/wasyncore.py", line 395, in bind
    return self.socket.bind(addr)
OSError: [Errno 98] Address already in use
